### PR TITLE
i149 collection metadata bug

### PR DESCRIPTION
**Pull request by ShanaLMoore**
Bug: A user imports a CSV to create a collection. When the user clicks Edit, the resource_link property doesn't persist. 

- [ ] This field should be read-only when editing/creating a collection. 
- [ ] This property can only be set via a bulkrax CSV import
- [ ] property uri has been updated per the client's changes

Sample File: [149-all-collection-metadata.csv](https://github.com/scientist-softserv/utk-hyku/files/9965988/149-all-collection-metadata.csv)

Screen Shot 2022-11-08 at 10 11 29 AM
Screen Shot 2022-11-08 at 10 12 14 AM
Screen Shot 2022-11-08 at 4 12 29 PM
Screen Shot 2022-11-08 at 10 11 44 AM

### CODE REVIEW

**Comment by ShanaLMoore** [comment]
Turns out that this was a local env issue. I needed to restart all of my docker containers for fedora to pick up the predicate url change. 

Solr was indexing it correctly but it was getting mapped to identifier in fedora. 

Screen Shot 2022-11-09 at 9 48 42 AM

Screen Shot 2022-11-09 at 9 43 01 AM

**Review by kirkkwang — APPROVED** [review]
Looks good, glad it worked out!!

**Comment by laritakr** [comment]
I thought we decided to remove BasicMetadata and IndexesBasicMetadata? Since `include Hyrax::IndexesLinkedMetadata` is now gone we shouldn't need it any more (or we can also do that in a separate issue if you prefer)

**Comment by ShanaLMoore** [comment]
> I thought we decided to remove BasicMetadata and IndexesBasicMetadata? Since `include Hyrax::IndexesLinkedMetadata` is now gone we shouldn't need it any more (or we can also do that in a separate issue if you prefer)

@laritakr - I started to go down that path but it was causing other issues with the collection form. I can make a separate ticket to do that but didn't want that work to be the blocker. 

Now none of their custom properties will conflict w the basic metadata so it should be ok leaving it for now.

**Pull request merged**
